name: E2E

on:
   push:
      - develop

jobs:
   add_version:
      runs-on: ubuntu-latest
      steps:
         -  uses: actions/checkout@v1

         -  run: sudo apt-get install sshpass

         -  run: sudo apt-get install pv

         -  run: docker build -t react-app:latest .

         -  run: docker save react-app:latest | bzip2 | pv | sshpass -p ${{ secrets.PASSWORD }} ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null root@devesharp.com 'bunzip2 | docker load'
